In [ ]:
import numpy as np

Additon in numpy

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr = arr + 2
arr

array([3, 4, 5, 6, 7])

In [ ]:
arr1 = np.array([5, 4, 3, 2, 1])
arr1 = arr + arr1
arr1

array([8, 8, 8, 8, 8])

In [ ]:
arr2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
arr3 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
arr2 = arr2 + arr3
arr2

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14]])

Numpy Substraction

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr - 1
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr1 = np.array([[1, 2, 3, 4, 5], [9, 8, 7, 6, 4]])
arr2 = np.array([[1, 2, 3, 4, 5], [9, 8, 7, 6, 4]])