In [ ]:
import numpy as np

ls = np.array([10, 20, 30, 40, 50, 60, 70, 80], dtype="int32")
ls

array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int32)

In [ ]:
print(np.sum(ls, dtype="int32"))
print(np.subtract(ls[4], ls[1]))

360
30


In [ ]:
for i in range(0, len(ls), 1):
    print(ls[i], end=" ")

10 20 30 40 50 60 70 80 

In [12]:
for i in ls:
    print(i, end=" ")

10 20 30 40 50 60 70 80 

In [ ]:
len(ls)

8

In [ ]:
arr = np.array([10, 112, 225, 1987], dtype="int16")
print(arr)

[  10  112  225 1987]


In [ ]:
brr = np.array([10.20, 55.30, 11.11, 99, 10])
print(brr)
brr = brr.astype(int)
print(brr)
print(brr[1:3])

[10.2  55.3  11.11 99.   10.  ]
[10 55 11 99 10]
[55 11]
