In [9]:
import numpy as np

arr1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr1.ndim

3

In [4]:
arr1.shape

(1, 3, 3)

In [8]:
arr1.itemsize

8

In [ ]:
arr2 = np.array([1, 2, 4.5])
arr2.itemsize
print(arr2)

[1.  2.  4.5]


<h1 style="color: red; font-size: 25px;"> Range - Zeros - Ones </h1>
Range np.arange(start,end, step)<br>
zeros np.zeros((shape)) <br>
ones np.ones((shape))


In [20]:
arr1 = np.arange(1, 10, 2)
print(arr1)
arr1 = np.arange(2, 10)
print(arr1)

[1 3 5 7 9]
[2 3 4 5 6 7 8 9]


In [23]:
arr1 = np.zeros((3, 4), dtype="int32")
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [24]:
arr = np.ones((3, 3), dtype="int64")
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

<h1 style="color: red; font-size: 25px;"> Identity Array </h1>
np.identity(n) -> makes an n*n diagonal 2d array <br>
np.eye(shape) -> makes an row * column diagonal array

In [36]:
arr = np.identity(4, dtype="int32")
print(arr)
arr = np.eye(5, 5, dtype="int32")
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


<h1 style="color: red; font-size: 25px;"> Lin Space </h1>
Lin space define np.linspace(start,end,how much element you want between start and end)

In [38]:
arr = np.linspace(1, 5, 5)
arr

array([1., 2., 3., 4., 5.])

<h1 style="color: red; font-size: 25px;"> reshape [np.reshape(dim,dim)] </h1>
* First you should declare a ndim array. <br>
* Then you can reshape according these. but if you reshape not according the original
    it may not work.
<h1 style="color: red; font-size: 25px;"> ravel [np.ravel()] </h1>
* it return ndim array to 1 dimensio array.

In [52]:
arr = np.array([[10, 20, 30, 40], [20, 30, 40, 50], [1, 2, 3, 4]])
print(arr.shape)
arr = arr.reshape(1, 12)
print(arr[0])

(3, 4)
[10 20 30 40 20 30 40 50  1  2  3  4]


In [ ]:
arr = np.array([[10, 20, 30, 40], [20, 30, 40, 50], [1, 2, 3, 4]])
print(arr.ravel())
print(arr.shape)

(3, 4)
